name: sdxl_lora
dataset: E:\IDrawing\ComfyUI-aki-v1.7\ComfyUI\output\lora_enc
model: E:\IDrawing\forge7\models\Stable-diffusion/bespokeillmix_v10.safetensors
output: ./ai-toolkit-output
# Optional writable cache dir for read-only datasets such as /kaggle/input.
# If omitted, the CLI defaults to <output>/<name>/dataset_cache.
# dataset_cache_dir: /kaggle/working/ai-toolkit-output/kaggle_sdxl_lora/dataset_cache

trigger_word: null
steps: 15000
batch_size: 2
gradient_accumulation: 1
lr: 0.0001
optimizer: adamw8bit
save_every: 1000
max_step_saves_to_keep: 15
save_best_model: true
sample_every: 1000

rank: 32
conv_rank: 16
resolution:
  - 512
  - 768
  - 1024
caption_ext: txt
cache_latents_to_disk: false
train_text_encoder: false
low_vram: false

dtype: fp16
save_dtype: float16
save_format: safetensors

decode_images: true
decode_key: 123456789

sample_prompts:
  - 1girl, anime coloring,dress,sfw,posing,embarrassed,thighhighs,
  - 1girl,anime coloring,maid,sfw,off shoulder,strapless,miniskirt,embarrassed,clothes,pull,loose socks,pose,dynamic emotion,
sample_neg: ""
sample_width: 1024
sample_height: 1024
sample_steps: 20
guidance_scale: 2.0
seed: 42
walk_seed: true
disable_sampling: false
no_skip_first_sample: false

# Optional:
# sample_prompts_file: /kaggle/input/prompts/prompts.txt
# config_path: /kaggle/working/generated_job_config.json
# log: /kaggle/working/train.log
# write_config_only: true
